# Generated by Django 5.2.4 on 2025-10-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teammates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammate",
            name="stack",
            field=models.CharField(default="New", max_length=64),
        ),
        migrations.AlterField(
            model_name="teammate",
            name="first_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="teammate",
            name="last_name",
            field=models.CharField(max_length=64),
        ),
    ]
