# Generated by Django 5.2.4 on 2025-10-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Active", max_length=20),
        ),
    ]
