# Generated by Django 5.2.4 on 2025-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="title",
            field=models.CharField(max_length=32),
        ),
    ]
